---
# packages.yml

- name: Zypper repositories
  command: >
    zypper addrepo {{ item.flags if 'flags' in item else ''}}
      {{ '--no-gpgcheck' if 'disable_gpg_check' in item else ''}}
      {{ item.repo }} {{ item.name }}
  args:
    creates: /etc/zypp/repos.d/{{ item.name}}.repo
  with_items: "{{ opensuse_repos }}"

- name: Remove systemd-logger (conflicts with rsyslog)
  zypper:
    name: systemd-logger
    state: absent

- name: Deal with missing --gpg-auto-import-keys ansible feature
  command: >
    zypper --gpg-auto-import-keys install -y mythtv-frontend
  args:
    creates: /usr/bin/mythfrontend

- name: Install system packages
  zypper:
    name: "{{ opensuse_packages }}"
