---
# network.yml

- name: Set static IP
  template:
    dest: /etc/network/interfaces.d/{{ network.interface }}
    src: interface.j2
  when: network.mode == 'static'

- name: Remove extraneous lines from network/interfaces
  replace:
    path: /etc/network/interfaces
    regexp: '^auto {{ network.interface }}$'
    replace: '# auto {{ network.interface }} - removed, see interfaces.d'
  when: network.mode == 'static'

- name: Remove extraneous lines from network/interfaces
  replace:
    path: /etc/network/interfaces
    regexp: '^iface {{ network.interface }} inet .*'
    replace: '# iface {{ network.interface }} - removed'
  when: network.mode == 'static'

- name: Reload Ethernet module upon wake-from-suspend
  template:
    dest: /etc/pm/sleep.d/20_eth_resume
    src: 20_eth_resume.j2
