---
# main.yml

- include: "{{ ansible_os_family | lower }}/packages.yml"
- include: "{{ ansible_os_family | lower }}/lirc.yml"
- include: "{{ ansible_os_family | lower }}/network.yml"
- include: autosuspend.yml
  when: suspend

- include: nvidia.yml
- include: setup.yml
- include: "{{ ansible_os_family | lower }}/desktop.yml"
