---
# main.yml

- name: Install system packages
  apt:
    name: "{{ ubuntu_packages }}"
  when: ansible_os_family == 'Debian'

- name: Create mount points
  file:
    dest: "{{ item.value.path }}"
    state: directory
  with_dict: "{{ luks_volumes | combine(network_mounts) |
                 combine(local_volumes) }}"

- name: Create volumes
  lvol:
    lv: "{{ item.key }}"
    vg: "{{ item.value.vg }}"
    shrink: no
    size: "{{ item.value.size }}"
  with_dict: "{{ luks_volumes }}"
  notify:
  - Cryptsetup resize
  - Filesystem resize

- include: encrypted.yml
- include: cifs.yml

- name: Network and local fstab entries
  mount:
    fstype: "{{ item.value.type if 'type' in item.value else fs_type }}"
    path: "{{ item.value.path }}"
    src: "{{ item.key }}"
    opts: "{{ item.value.options if 'options' in item.value else 'defaults' }}"
    state: mounted
  with_dict: "{{ network_mounts | combine(local_volumes) }}"
